version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - rdarida
  assignees:
  - rdarida
  labels:
  - dependencies
  versioning-strategy: increase
